import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Toaster } from "sonner";
import Logo from "@/components/Floating/Logo";



const space = Space_Grotesk({
 subsets:["latin"]
});

<html className={space.className}></html>

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-black text-white">

        <Navbar />

        {/* fixed navbar ka space */}
        <main className="flex-1 pt-20">
          {children}
           <Toaster
          position="top-right"
          richColors
          closeButton
        />

        </main>

        <Footer />

        {/* floating logo */}
        <Logo />

      </body>
    </html>
  );
}
